//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.03 at 03:24:03 PM PST 
//


package com.mitchell.JXAB.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimantFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimantLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LossDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="LossInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CauseOfLoss" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AssignedAdjusterID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="Vehicles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="VehicleDetails">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="MakeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ModelDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EngineDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LicPlate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LicPlateState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="LicPlateExpDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="DamageDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "claimNumber",
    "claimantFirstName",
    "claimantLastName",
    "status",
    "lossDate",
    "lossInfo",
    "assignedAdjusterID",
    "vehicles"
})
@XmlRootElement(name = "MitchellClaim")
public class MitchellClaim {

    @XmlElement(name = "ClaimNumber", required = true)
    protected String claimNumber;
    @XmlElement(name = "ClaimantFirstName", required = true)
    protected String claimantFirstName;
    @XmlElement(name = "ClaimantLastName", required = true)
    protected String claimantLastName;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "LossDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lossDate;
    @XmlElement(name = "LossInfo", required = true)
    protected MitchellClaim.LossInfo lossInfo;
    @XmlElement(name = "AssignedAdjusterID")
    protected short assignedAdjusterID;
    @XmlElement(name = "Vehicles", required = true)
    protected MitchellClaim.Vehicles vehicles;

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the claimantFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantFirstName() {
        return claimantFirstName;
    }

    /**
     * Sets the value of the claimantFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantFirstName(String value) {
        this.claimantFirstName = value;
    }

    /**
     * Gets the value of the claimantLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantLastName() {
        return claimantLastName;
    }

    /**
     * Sets the value of the claimantLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantLastName(String value) {
        this.claimantLastName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the lossDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLossDate() {
        return lossDate;
    }

    /**
     * Sets the value of the lossDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLossDate(XMLGregorianCalendar value) {
        this.lossDate = value;
    }

    /**
     * Gets the value of the lossInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MitchellClaim.LossInfo }
     *     
     */
    public MitchellClaim.LossInfo getLossInfo() {
        return lossInfo;
    }

    /**
     * Sets the value of the lossInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MitchellClaim.LossInfo }
     *     
     */
    public void setLossInfo(MitchellClaim.LossInfo value) {
        this.lossInfo = value;
    }

    /**
     * Gets the value of the assignedAdjusterID property.
     * 
     */
    public short getAssignedAdjusterID() {
        return assignedAdjusterID;
    }

    /**
     * Sets the value of the assignedAdjusterID property.
     * 
     */
    public void setAssignedAdjusterID(short value) {
        this.assignedAdjusterID = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link MitchellClaim.Vehicles }
     *     
     */
    public MitchellClaim.Vehicles getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link MitchellClaim.Vehicles }
     *     
     */
    public void setVehicles(MitchellClaim.Vehicles value) {
        this.vehicles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CauseOfLoss" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "causeOfLoss",
        "reportedDate",
        "lossDescription"
    })
    public static class LossInfo {

        @XmlElement(name = "CauseOfLoss", required = true)
        protected String causeOfLoss;
        @XmlElement(name = "ReportedDate", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar reportedDate;
        @XmlElement(name = "LossDescription", required = true)
        protected String lossDescription;

        /**
         * Gets the value of the causeOfLoss property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCauseOfLoss() {
            return causeOfLoss;
        }

        /**
         * Sets the value of the causeOfLoss property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCauseOfLoss(String value) {
            this.causeOfLoss = value;
        }

        /**
         * Gets the value of the reportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReportedDate() {
            return reportedDate;
        }

        /**
         * Sets the value of the reportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReportedDate(XMLGregorianCalendar value) {
            this.reportedDate = value;
        }

        /**
         * Gets the value of the lossDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLossDescription() {
            return lossDescription;
        }

        /**
         * Sets the value of the lossDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLossDescription(String value) {
            this.lossDescription = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="VehicleDetails">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="MakeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ModelDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EngineDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LicPlate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LicPlateState" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="LicPlateExpDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="DamageDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vehicleDetails"
    })
    public static class Vehicles {

        @XmlElement(name = "VehicleDetails", required = true)
        protected MitchellClaim.Vehicles.VehicleDetails vehicleDetails;

        /**
         * Gets the value of the vehicleDetails property.
         * 
         * @return
         *     possible object is
         *     {@link MitchellClaim.Vehicles.VehicleDetails }
         *     
         */
        public MitchellClaim.Vehicles.VehicleDetails getVehicleDetails() {
            return vehicleDetails;
        }

        /**
         * Sets the value of the vehicleDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link MitchellClaim.Vehicles.VehicleDetails }
         *     
         */
        public void setVehicleDetails(MitchellClaim.Vehicles.VehicleDetails value) {
            this.vehicleDetails = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="MakeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ModelDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EngineDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LicPlate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LicPlateState" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="LicPlateExpDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="DamageDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vin",
            "modelYear",
            "makeDescription",
            "modelDescription",
            "engineDescription",
            "exteriorColor",
            "licPlate",
            "licPlateState",
            "licPlateExpDate",
            "damageDescription",
            "mileage"
        })
        public static class VehicleDetails {

            @XmlElement(name = "Vin", required = true)
            protected String vin;
            @XmlElement(name = "ModelYear")
            protected short modelYear;
            @XmlElement(name = "MakeDescription", required = true)
            protected String makeDescription;
            @XmlElement(name = "ModelDescription", required = true)
            protected String modelDescription;
            @XmlElement(name = "EngineDescription", required = true)
            protected String engineDescription;
            @XmlElement(name = "ExteriorColor", required = true)
            protected String exteriorColor;
            @XmlElement(name = "LicPlate", required = true)
            protected String licPlate;
            @XmlElement(name = "LicPlateState", required = true)
            protected String licPlateState;
            @XmlElement(name = "LicPlateExpDate", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar licPlateExpDate;
            @XmlElement(name = "DamageDescription", required = true)
            protected String damageDescription;
            @XmlElement(name = "Mileage")
            protected short mileage;

            /**
             * Gets the value of the vin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVin() {
                return vin;
            }

            /**
             * Sets the value of the vin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVin(String value) {
                this.vin = value;
            }

            /**
             * Gets the value of the modelYear property.
             * 
             */
            public short getModelYear() {
                return modelYear;
            }

            /**
             * Sets the value of the modelYear property.
             * 
             */
            public void setModelYear(short value) {
                this.modelYear = value;
            }

            /**
             * Gets the value of the makeDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMakeDescription() {
                return makeDescription;
            }

            /**
             * Sets the value of the makeDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMakeDescription(String value) {
                this.makeDescription = value;
            }

            /**
             * Gets the value of the modelDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModelDescription() {
                return modelDescription;
            }

            /**
             * Sets the value of the modelDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModelDescription(String value) {
                this.modelDescription = value;
            }

            /**
             * Gets the value of the engineDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEngineDescription() {
                return engineDescription;
            }

            /**
             * Sets the value of the engineDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEngineDescription(String value) {
                this.engineDescription = value;
            }

            /**
             * Gets the value of the exteriorColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExteriorColor() {
                return exteriorColor;
            }

            /**
             * Sets the value of the exteriorColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExteriorColor(String value) {
                this.exteriorColor = value;
            }

            /**
             * Gets the value of the licPlate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLicPlate() {
                return licPlate;
            }

            /**
             * Sets the value of the licPlate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLicPlate(String value) {
                this.licPlate = value;
            }

            /**
             * Gets the value of the licPlateState property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLicPlateState() {
                return licPlateState;
            }

            /**
             * Sets the value of the licPlateState property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLicPlateState(String value) {
                this.licPlateState = value;
            }

            /**
             * Gets the value of the licPlateExpDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getLicPlateExpDate() {
                return licPlateExpDate;
            }

            /**
             * Sets the value of the licPlateExpDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setLicPlateExpDate(XMLGregorianCalendar value) {
                this.licPlateExpDate = value;
            }

            /**
             * Gets the value of the damageDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDamageDescription() {
                return damageDescription;
            }

            /**
             * Sets the value of the damageDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDamageDescription(String value) {
                this.damageDescription = value;
            }

            /**
             * Gets the value of the mileage property.
             * 
             */
            public short getMileage() {
                return mileage;
            }

            /**
             * Sets the value of the mileage property.
             * 
             */
            public void setMileage(short value) {
                this.mileage = value;
            }

        }

    }

}
